// <auto-generated />
namespace CodeFirst1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updateTableeesss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTableeesss));
        
        string IMigrationMetadata.Id
        {
            get { return "202409181409168_updateTableeesss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
