// <auto-generated />
namespace CodeFirst1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class oneTomanyTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oneTomanyTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202409181405439_oneTomanyTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
